### ISSUE TITLE
Inconsistent use of systems of measure

### ISSUE THREAD

**Issue by tarsiec** [LukeSmithxyz/based.cooking#143]
Every recipe in the site has a different (or no) system of measure, some use metric and others imperial. It'd be a nice feature to have either different pages to see the recipes in metric or imperial, or some other feature like that (obviously without the use of JavaScript). Or maybe just have them all in metric, whichever works.

**Comment by siggines** [comment]
Just use a metric-imperial converter, I have one /siggines/unit-conversions . Also helps show how they can be converted, which is helpful to understand so you can convert in your head when reading future uses of the imperial.

**Comment by Godje** [comment]
I suggest putting something in the "Rules of submission", and "About this site" description, that the recipes must be submitted in *one* form of system. The conversion would be up to the person reading the recipe.

This way we are avoiding the author hastily approximating in both systems of measurement (ex. https://based.cooking/beef-jerky), where either one of them is not correct or doesn't match the other.

**Or** the other way of solving this is in the rules of submission to have the person do the conversion of both. This way we are ensuring the quality of submissions is held to a higher standard. Since we want this website to be actually used by a normal human person, rather than a bunch of "special" people like ourselves.

**Comment by Godje** [comment]
Take my words back.

And suggest that we put in the section like a "dictonary" of sorts. A person might have to do 3 or so look ups on the bloated interwebs to see what cL means (centiliter). 

While the amount of contributors to this website is growing, it would be useful in the rules of submission to have an outlined way of writing Tablespoon vs Teaspoon (etc.), until we see recipes with "4ts of lemon squeezed lemon juice" and leave the reader guessing.

**Comment by owwk** [comment]
Just require that all recipes include both, with one in brackets. Recipe books in countries that have switched to using metric do this.

e.g. 
Flour 600g (21oz)

Whether the metric or imperial measurement is in brackets doesn't really matter, but it would be nice it it was kept consistent across the site.

**Comment by Godje** [comment]
Thinking technically, during compile time we could put in a pre-processor with some sort of custom tag recognition and convert it automatically. And round to nearest 1st or 2nd decimal spot.

Although that's "too accurate" lol :)

**Comment by murphym18** [comment]
Unit conversion can be pretty tricky. [This video](https://www.youtube.com/watch?v=TE8xg3d8dBg) does a pretty good job explaining the problems.

Sometimes direct unit conversions plus some clever rounding is good enough. But even simple recipes can be deceptively tricky to convert. Consider the [roasted chicken breast](https://based.cooking/roasted-chicken-breast) recipe that I added. It's almost a recipe that someone in Europe could follow. But it calls for "1/4 stick of butter." That much butter only makes sense to Americans and Canadians. A direct conversion would give a result of 28.35 grams (1/4 stick = 1 oz = 28.35 grams). But the exact amount of butter isn't too important (I use a generous amount of butter so that I can make a pan sauce out of the extra). 

I think the best way to fix that recipe is for someone from outside North America to edit it. It's not obvious how people measure butter through out the world. I looked at pictures of butter in a German supermarket. They sold it as a single brick massing 125 grams or 250 grams. And I think it would be silly to actually measure out 25 grams of butter. I thought about using the British idiom: "a large knob of butter." (I guess that's about 25 grams). Overall, I'm not sure. It would be useful to know what people actually do when they measure butter.

Until then, I thought about updating my recipe to say "about 25 grams" or something. But even that might be awkward. What if saying 25 grams is like saying "0.3 inches?" (In case you don't know, inches are usually measured as fractions where the denominator is a power of 2. So "0.3 inches" would probably be specified as "5/16 inches" or "19/64 inches" as those are idiomatic values). I'm pretty sure most people just uses a digital kitchen scale (so "25 grams" is fine). But what if analog kitchen scale are more common? How do those analog scales divide the units?

Another idea is to put something in the README that encourages people to make pull requests for unit conversion. But I think this only makes sense when the contributor specifies a roughly equivalent amount and does so idiomatically. Even then, I'm sure there will be many recipes that don't convert well. And putting something like that in the README might cause more harm than good. 

A computer program that converts units is still probably valuable. Though, a human could probably do a better job. I think it would be good if such a program didn't output units if someone manually converted them. And it might be good to style the units different when a computer converted them. I'm not sure.

Maybe we should train a model to detect when equivalent units are missing. (🤣 I'm only half joking).

**Comment by LukeSmithxyz** [comment]
I am fine with people using whatever measurement system they want. Autoconverting measurements is absurdly impossible. Me nit-picking every PR to format everything exactly the same is going to be too annoying too. I've already realized I'm going to have to leave some things to personal idiosyncracy.

Every English speaker is used to using both measurement systems so I don't really think this is a huge issue outside of being displeasurable to one's autism.

If I were to choose one, I would enforce the American measurements, of course. There really is something truly absurd to me about measuring food in soulless French revolutionary bugman measurements. It seems cold and alien. "No, I don't want to use that 'cup' thing there to make a measurement, I would rather calculate the ingredients to my confection in SI because it can be multiplied and divided equally by 10."

**Comment by Dko1905** [comment]
@LukeSmithxyz 

> Every English speaker is used to using both measurement systems so I don't really think this is a huge issue outside of being displeasurable to one's autism.

Every American maybe, but not every English speaker, statista.com claims that 3-4 countries in the whole world use imperial units, so there are a lot of us that would need to convert imperial into SI units.

> If I were to choose one, I would enforce the American measurements, of course. There really is something truly absurd to me about measuring food in soulless French revolutionary bugman measurements. It seems cold and alien. "No, I don't want to use that 'cup' thing there to make a measurement, I would rather calculate the ingredients to my confection in SI because it can be multiplied and divided equally by 10."

I would say you are overreacting a bit there, it's simpler when using one unified system for everything. But let's not start that discussion.

**Comment by tarsiec** [comment]
>There really is something truly absurd to me about measuring food in soulless French revolutionary bugman measurements. It seems cold and alien. "No, I don't want to use that 'cup' thing there to make a measurement, I would rather calculate the ingredients to my confection in SI because it can be multiplied and divided equally by 10."

Well that's just because you've been using the imperial system all of your life, but to the rest of the world using things like "cups" to measure volume just seems archaic and purposefully overcomplicated.
