### ISSUE TITLE
Make the recipes DRY!

### ISSUE THREAD

**Issue by syntacticallyWrong** [LukeSmithxyz/based.cooking#259]
If 50 recipes have you boil spaghetti for example, why not just make a spaghetti recipe and import it into all the other recipes that use it? (Spaghetti is an example, but you get the idea.)

With this you can make a lot of other stuff easier too, like adding ingredients and nutrients automatically by just importing a "sub-recipe" for the desired dish.

There are multiple ways to implement this, so suggestions in how this would be done in the best way possible is appreciated!

**Comment by LukeSmithxyz** [comment]
Well, that's exactly what I originally had. That's why, for example, the "Pasta (store bought)" page exists, to be linked from others.

Unfortunately few have followed the example so I need to say it more explicitly in the README or enforce it.

**Comment by sylGauthier** [comment]
People just have to properly link recipes together like `[Recipe name](recipe-file-name.html)`, using **relative**links so that the linking works even if people are hosting their own instances.

I am against "injecting" recipes into each other, useless complexity when hyperlinks already exist for this very purpose.

**Comment by zyansheep** [comment]
Maybe add something to the Readme that says put hyperlink to ingredient (relative or external) in parentheses after each ingredient if possible.

**Comment by Bumbadawg** [comment]
Would love to contribute to some recursive recipe.
