### ISSUE TITLE
"make build" fails

### ISSUE THREAD

**Issue by alpo** [LukeSmithxyz/based.cooking#287]
"make build" fails with error message:
```
/bin/sh: 9: Syntax error: "(" unexpected
Makefile:65: recipe for target 'blog/index.html' failed
```
It would have been polite to mention which version of make and which shell are required.
I have GNU make 4.1 and zsh 5.4.2.

**Comment by Goblin80** [comment]
It's kinda not the makefile's fault.

The build is breaking due to 2 rouge files.

* src/Classic-bechamel-sauce
* src/schinkenfleckerl-gratinated

these 2 files should have an .md extenstion and lowercased. which is clearly an oversight on the maintainer.

for the time being, remove theses files and **commit**.

Since the makefile grabs the list of recipes using git:

```bash
ARTICLES = $(shell git ls-tree HEAD --name-only -- $(BLOG_SRC)/ 2>/dev/null)
```

**Comment by alpo** [comment]
I suspected the shell issue because when I replaced all "$(shell" with "$(bash" in the Makefile everything works fine.

**Comment by adeptflax** [comment]
What's the program that's used for the "markdown" command?

**Comment by Morelcia** [comment]
> What's the program that's used for the "markdown" command?

discount

**Comment by adeptflax** [comment]
it doesn't build with css. How do I fix?

**Comment by Morelcia** [comment]
Move css manually from data to blog. 
make deploy from github actions does that automatically

**Comment by adeptflax** [comment]
ok

**Comment by adeptflax** [comment]
There's no link tag in the index.html. make deploy just does rsync.

**Comment by aaraney** [comment]
This comment is not directly related to the above conversation, but instead the overarching subject. I just wanted to note that the Makefile target `build` will not work on OSX as of c3b8ff6. This is because OSX uses BSD `sed` instead of GNU `sed` (to resolve, one option is to install `gnu-sed` via homebrew). Given the purpose of this project, I don't think this incompatibility requires any attention, I just wanted to note it for others who may come looking in the future.
