### ISSUE TITLE
You can use plainoldrecipe for creating new pages

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/based.cooking#31]
https://github.com/poundifdef/plainoldrecipe

**Comment by asakura42** [comment]
This script uses https://github.com/hhursev/recipe-scrapers and test it at https://www.plainoldrecipe.com/

**Comment by robertefry** [comment]
I'm not a lawyer, but I'm pretty sure there'll be some licensing issues copy/pasting plaintext from another website.
Great website though, and probably still good for ""inspiration"".

**Comment by LukeSmithxyz** [comment]
Well, to my understanding, in the US and most other places, recipes are not subject to copyright.

This is partially why so many food-blogger embellish their posts with personal anecdotes and such: they want to get copyright status on the blog post generally as a literary work, but the substance of a recipe is not subject to copyright.

It's fine if someone wants to use a tool like this, but I'd sort of prefer people add things they are familiar with and can vouch for rather than roboticly prodooocing content via crawling scripts.

**Comment by asakura42** [comment]
@LukeSmithxyz 
I don't know where to write, but you'll probably notice this post here. I recently found a number of similar sites from a developer who is trying to replace JS sites with simple equivalents. For example, https://simpleertube.metalune.xyz/videos.lukesmith.xyz/ (js-free peertube viewer), https://translate.metalune.xyz (js-free g**gle translate), https://freebay.metalune.xyz/ (ebay search) and even js-free adult website. I hope that there will be more and more projects like this.
