### ISSUE TITLE
How to create other instances ?

### ISSUE THREAD

**Issue by HappyClem** [LukeSmithxyz/based.cooking#409]
New here.

How could we be able to create ourselves other instances of base-cooking ?
Like I would really be down to make a french version of the site but I have absolutely no idea how to make a fork into a actual website. (I'm just a 2 years old html/css dev).
I never heard about static site generator before this and it sounds amazing, and I have no idea what it really does, nor how to create one.

I'm sure this isn't fit to be in issues but idk where else to post this. If you have any idea I'd be more than happy !

**Comment by hallzy** [comment]
The static site generator is just the make file.

You basically run `make build` and the makefile goes through your source files and converts them into an HTML file each, and creates HTML files for your tags etc.

I think the only dependency to build is `discount` which is a program that is able to convert your markdown to html files.

So, if you want to do your own thing, you could just take the basic structure of this repository, and change the source files to recipes that fit what you want, and use the makefile to build your html files.

The static site generator used here is called [blogit](https://pedantic.software/git/blogit) which was added to this project by one of its maintainers.

**Comment by HappyClem** [comment]
So once I installed blogit, forked the project, directed the project in blogit, i can go on and add recipes in my languages ? It sounds simple, yet i'm afraid. How after tat can i host this site ? ^^' I wish there were private tchat but I can't find them if it exists, sorry. (and thank you for the info !!).

**Comment by hallzy** [comment]
> i can go on and add recipes in my languages ?

Just to be clear, you are meaning that you want to translate the recipes into french right? Not using some different syntax that isn't markdown?

If you are using a different markup language that isn't markdown then it won't work, but just translating the content from one human language to another should have no problems.

> if i forked the repo and change the css for exmeple, if I update the fork from the original, is my custom files gonna be "updated" (replaced ?

I am not 100% sure what you mean.

I have no idea how familiar you are with git/github and forks so I'll try and explain it like you don't just to be safe.

When you fork a repository on github by clicking the 'fork' button in the top right corner of a repo what github does is it clones the repository, and saves a copy under your username. For all intents and purposes, it is 100% separate from the original, but you are able to merge in changes from the original if you want.

So if you fork this repo and change the CSS, that is totally fine. That fork is now yours and nothing that is done here will affect your fork at all, unless you actively merge in changes yourself.

Your fork won't get updates automatically from this repo, so your changes won't be updated or replaced.

But as mentioned, if you want to take updates from this repo, you can do that... you just need to use git to merge it in. In this case, if you have changed the CSS in your fork, and somebody else has changed the same CSS in this repo, you will get a merge conflict. So your changes won't be overwritten, but git will ask you to manually decide which changes to keep because it doesn't know if you want the changes from this repo, or your fork, or maybe a combination of both.

Hopefully that answered your question?

**Comment by HappyClem** [comment]
It answered some it yes thanks !
I don't intent to use anither language then markup. The whole idea is to create a dedicated site, using this base, for recipes in french (using the markup syntax). Am i right in the process of getting started at least ? I'm completly in the fog for hosting atm but that's a second part.

**Comment by hallzy** [comment]
yup seems like you are going in the right direction. I'd suggest trying to get the files to build correctly first. Once the build goes through you should be able to open up the `blogit/index.html` file in a browser and you should be able to navigate the site. I think the CSS file isn't moved though so the styling probably won't be applied, but that would be a good starting place.

Next get it hosted before spending time translating. Because at least if you can get that out of the way then you don't need to worry about it anymore.

As for how to host... There are a ton of ways to host a website. If I remember correctly, Luke has at least one video on how to host a website.

github also provides a way to host websites within a repository using a github url which will look something like `<username>.github.io/<project name>`

You can setup hosting on github by going to `Settings` in your repository and scrolling down to `GitHub Pages`, and basically set that all up there. In order to do it this way though, you'll have to commit the html files that blogit generates as well (which we don't do here). That is because github pages uses the files in your repository as the website. You also can't use server scripting using this, so no PHP or Node or anything. This project doesn't use PHP or node though so you are fine.

**Comment by HappyClem** [comment]
Omg ! Thanks for the help ! I will try my absolute best to make this happens, in the near future ^^'
I thank that hosting it on github would be a great idea indeed. It's jsut the setup phase that scaring me, server stuff is always a hastle for me. Thanks a lot ! And I hope this can hlep others ! (don't really if it fits here tho).

**Comment by hallzy** [comment]
good luck :D
