### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by Mentis-Moldvin** [LukeSmithxyz/based.cooking#501]
This project, I am afraid, lacks proper and **inclusive** CoC.
As of right now there is no obvious way for a disabled trans person to contribute to this project other than to obey the normative rules derived from the patriarchal world, something we must strive to change. As a trans-race biPoC of color, and disabled non-genius (I induced clinical retardation by lowering my IQ from 140 to roughly 100 with microdosing) I feel obliged to remind you to write proper CoC for this project, since I don't feel safe around all non-trans people.
Thank you for your time.

**Comment by DGKSK8LIFE** [comment]
> This project, I am afraid, lacks proper and inclusive CoC.
As of right now there is no obvious way for a disabled trans person to contribute to this project other than to obey the normative rules derived from the patriarchal world, something we must strive to change. As a trans-race biPoC of color, and disabled non-genius (I induced clinical retardation by lowering my IQ from 140 to roughly 100 with microdosing) I feel obliged to remind you to write proper CoC for this project, since I don't feel safe around all non-trans people.
Thank you for your time. 

Profile pic matches up, yep he's trolling

**Comment by Mentis-Moldvin** [comment]
> > This project, I am afraid, lacks proper and inclusive CoC.
> > As of right now there is no obvious way for a disabled trans person to contribute to this project other than to obey the normative rules derived from the patriarchal world, something we must strive to change. As a trans-race biPoC of color, and disabled non-genius (I induced clinical retardation by lowering my IQ from 140 to roughly 100 with microdosing) I feel obliged to remind you to write proper CoC for this project, since I don't feel safe around all non-trans people.
> > Thank you for your time.
> 
> Profile pic matches up, yep he's trolling

yes, thats the type of behavior I am trying to avoid, right now without CoC, people like me are left to the sharks

**Comment by DGKSK8LIFE** [comment]
> This project, I am afraid, lacks proper and inclusive CoC.
As of right now there is no obvious way for a disabled trans person to contribute to this project other than to obey the normative rules derived from the patriarchal world, something we must strive to change. As a trans-race biPoC of color, and disabled non-genius (I induced clinical retardation by lowering my IQ from 140 to roughly 100 with microdosing) I feel obliged to remind you to write proper CoC for this project, since I don't feel safe around all non-trans people.
Thank you for your time.

Profile pic matches up, yep he's trolling

yes, thats the type of behavior I am trying to avoid, right now without CoC, people like me are left to the sharks

You're actually trolling. Before you had a based pepe profile picture lol.

**Comment by Mentis-Moldvin** [comment]
> You're actually trolling. Before you had a "based pepe" profile picture lol.

and how does this nice looking bear with cowboy hat refute your argument exactly? I can still be trolling even with that pic
nevertheless, my pic is not to be commented here

**Comment by DGKSK8LIFE** [comment]
@LukeSmithxyz close.

**Comment by Mentis-Moldvin** [comment]
> @LukeSmithxyz close this.

@LukeSmithxyz don't close it, before you create a proper CoC.

**Comment by zyansheep** [comment]
suggestion for CoC: don't be a dick and treat other people how you want to be treated
opinion: this is an unstated rule of just being a normal person
conclusion: we don't need a CoC

**Comment by KiChesney** [comment]
Create a privilege lookup table by assigning a privilege value to each trait (race, gender, etc)

Then ban anyone below a certain privilege threshold from interacting with the project in any way so we don't have to see posts like this ever again

**Comment by Mentis-Moldvin** [comment]
> Create a privilege lookup table by assigning a numerical privilege value to each trait (race, gender, etc)
> 
> Then ban anyone below a certain privilege threshold from interacting with the project in any way so we don't have to see posts like this ever again

this is something I can stand behind, but not banning, rather empower them proportionate to their missing points in privilege
