### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by DarkWiiPlayer** [LukeSmithxyz/based.cooking#51]
There's a checkbox somewhere in the project settings

**Comment by m-chrzan** [comment]
Why do you feel this would be necessary/useful? These are very useful when you have users of a software product that will be troubleshooting issues. This is just a website, Issues seem like a an adequate forum for any discussions.

**Comment by DarkWiiPlayer** [comment]
Stuff like "how much javascript, if any at all, os acceptable?" "What should CSS look like if it's added?" etc.

**Comment by Naheel-Azawy** [comment]
Opening an issue here would be kinda messy I guess. Issues here would be more about the website itself rather than the recipes.

People usually use "disqus" which I'm not a big fan of. There are lots of javascripty self-hosted alternatives like [mouthful](https://github.com/vkuznecovas/mouthful) and [isso](https://github.com/posativ/isso).
But it doesn't really need to be done with javascript. Commenting can be as simple as submitting a form in html and the server stores it in a database. When loading a recipe page, the server loads the comments from the database and add them to the bottom of the html body. I'm not sure if someone has implemented this before but I guess it won't be that complicated. But of course more load would be added to the server in this case.

Another idea can be to simply create another repo only for discussions about recipes. But that would be still not so clean in my opinion.

**Comment by DarkWiiPlayer** [comment]
What I mean is mostly that github issues often get misused for very generic discussions instead of what they should be used for: single **issues** that a project has. Github discussions does a good job at separating the two into different categories with slightly different tooling so I'd like to see them enabled for this repository.
