### ISSUE TITLE
Option to submit recipe for normies

### ISSUE THREAD

**Issue by Rexadev** [LukeSmithxyz/based.cooking#706]
I can be like wikipedia people can discus make corrections, make variants of recipes
Call it OpenFoodProject 
Also I want PDF

**Comment by wups** [comment]
Simply add an email address for submitting recipes to the site with a note, that Github is the preferred way.
Someone would need to volunteer for transferring these recipes to Github, though.
This can be automated using a script, after manually checking the content of the email, of course.

**Comment by opaldes** [comment]
Most webbrowsers have a print as pdf option when you try to print the page.
Everything you want is possible inside github, if you disagree with a recipe you can create an issue, variants are somewhat not wished, they would add bloat if we got 10 diffferent recipes for the same thing. Variants have maybe a place inside the main dish as optional.

**Comment by Rexadev** [comment]
> Most webbrowsers have a print as pdf option when you try to print the page. Everything you want is possible inside github, if you disagree with a recipe you can create an issue, variants are somewhat not wished, they would add bloat if we got 10 diffferent recipes for the same thing. Variants have maybe a place inside the main dish as optional.

For cooking having variants is better than Wikipedia style because
that why normies can also contribute to the project and cooking is subject people may comment on it.
No way we are getting chief with science degrees arguing about the perfect recipe.

**Comment by opaldes** [comment]
I just think there are 2 ways how variants behave in cooking:

A.)they are trivial, like changing the type of meat, you can make a chicken parmesan with beef or pork.

B.)they are big, carbonara is parmesan eggyolk starchwater white wine and guancale, making a variant with cream, canadian bacon and garlic is something ppl would offer at bad italien restaurants as carbonara.

The site clearly doesnt want type A of variants, they are just bloat.

Type B are not variants, they are basicly different recipes with the same Name, even then we probably only need a single recipe as adding cream to make it more creamy or using canadian bacon instead of guancale can be part of optional ingredients. So you could add to ingredients: 100grams of either guancale or bacon.

Comments would add bloat, server sided logic(you need a DB for comments) and even worse need someone to moderate it.


Creating an automatet way like @wups would fail without a user who controlls them, else we get equal recipes because of a typo, how could an algorithm know that a recipe for "pizza" == "pizza pie", we would be littered with sameish recipes.

If you think its important to have a certain recipe on based.cooking you can learn git or open an issue with the recipe and ask someone to open up a pull req.
