### ISSUE TITLE
Multilingual Mode - Hugo

### ISSUE THREAD

**Issue by lisbonjoker** [LukeSmithxyz/based.cooking#759]
Like my previous suggestion - https://github.com/LukeSmithxyz/based.cooking/issues/666
Introducing localization to based.cooking to be of used to all around the world!

Info: https://gohugo.io/content-management/multilingual/

**Comment by ermitxyz** [comment]
I was about to suggest just that.
When I show this page to my mother and sister they really like the idea but did't understand english that well and it was a little inconvinient because we don't want to use google translate (this is sadly a common practice).

It would be good for people that don't understand english good enough and also for independence of google services!

**Comment by LukeSmithxyz** [comment]
I can't myself manage this. If you PR stuff that works though, I'll consider it. Just don't expect me to do this myself, especially for languages I don't know.

There are some other metadata issues I think should be Hugoized, like prep time and stuff before adding a whole nother version of the site.

**Comment by lisbonjoker** [comment]
Will work on it then, I'll handle Portuguese language.
