### ISSUE TITLE
Recipe list bug

### ISSUE THREAD

**Issue by liconver** [LukeSmithxyz/based.cooking#781]
I get a bug when I first load the page on a desktop browser and some of list elements are overlapping each other.  There are two columns of list elements but a chunk of the first column is missing and is being rendered over top of the second column.  I don't know what's causing it but I wonder why the script tag is placed where it is without the 'async' or 'defer' attributes.  Looks like this repo is more about recipe submissions that for editing source code though.

**Comment by geowy** [comment]
@liconver I wasn't able to reproduce this. Can you add a video or screenshot? Or at least let people know your browser, OS, resolution, etc?

It sounds more like a browser rendering bug than something caused by JS. All the JS does is toggle a class.

**Comment by liconver** [comment]
![image](https://user-images.githubusercontent.com/38049955/174485068-5684d89c-8d77-4b5f-92c1-32186ed4cfdd.png)

I'm using the current version of Brave browser on Windows 10.  I just tried loading the page with MS Edge and this issue didn't occur in that browser but I don't normally use edge.

**Comment by LukeSmithxyz** [comment]
I can't replicate this either. Works on Brave for GNU/Linux. The issue would not be the JS, but the responsive CSS or how Windows Brave renders the multicolumn list.

**Comment by liconver** [comment]
Well then why does my browser only render this webpage this way?  I'm willing to bet it has something to do with the way the DOMContentLoaded event is being used here.

**Comment by geowy** [comment]
<img width="710" alt="Screen Shot 2022-06-20 at 8 17 39 am" src="https://user-images.githubusercontent.com/5038349/174506066-2b5739e8-93ab-4009-a1a0-551ca8379b07.png">

Just found out I can reproduce on Mac OS + Edge. Just navigate to based.cooking and hit refresh until you see it.

I don't think it's JS because it still happens with JS disabled. My guess is it's a browser rendering bug.

**Comment by liconver** [comment]
It only seems to happen on the first page load, so to be able to explore a fix you would probably need access to the source code that Hugo is using which I don't see in this repo

**Comment by lacamera** [comment]
@liconver If you want to debug/build the site on your machine you need to:
```sh
git clone https://github.com/LukeSmithxyz/based.cooking.git
cd based.cooking
mkdir -p themes
git clone https://github.com/LukeSmithxyz/lugo.git themes/lugo

# the web server binds to locahost:1313 by default
hugo server -D
```
I will submit a PR to update the README to include the build steps later today.
Cheers

**Comment by lacamera** [comment]
> It only seems to happen on the first page load, so to be able to explore a fix you would probably need access to the source code that Hugo is using which I don't see in this repo

Strange, on my end (OpenBSD chromium v102.0.5005.115) the issue is persistent. Reloading the page does not  change the behaviour of the list items.

**Comment by lacamera** [comment]
> I will submit a PR to update the README to include the build steps later today.
README updated to reflect said changes in https://github.com/LukeSmithxyz/based.cooking/pull/790

**Comment by LukeSmithxyz** [comment]
I've replicated this on ungoogled-chromium.

The issue is definitely not Javascript related. You can turn off JS in your browser or remove the script altogether from the source and the issue persists in Chromium browsers.

It's worth noting as well that this site has had multiple columns for over a year now and no one has complained until now: I'm guessing that there was a webkit update or something else that screwed this up (although a problem this big slipping through is suspect). Although there might be a way around this issue.
