### ISSUE TITLE
Improve adherence to standards & best practices

### ISSUE THREAD

**Issue by geowy** [LukeSmithxyz/based.cooking#788]
* Standards – there are about a dozen HTML errors
https://validator.w3.org/nu/?showimagereport=yes&doc=https%3A%2F%2Fbased.cooking%2F
* Best practices – does pretty well, but there are still a few things that can be improved
https://web.dev/measure/?url=https%3A%2F%2Fbased.cooking%2F

I'm happy to fix these up myself but just wanted to make sure my pull request has a chance of being merged first

**Comment by geowy** [comment]
@LukeSmithxyz feel free to give me the go-ahead or close the issue if not interested

**Comment by LukeSmithxyz** [comment]
In a98188000e2a57c088ab1637baaa0efb47e76db4, I've allowed it so you can set a `description` metadata variable in the markdown, or otherwise it will use Hugo's native `{{ .Summary }}` feature that takes a description from the first part of the text.

That is an improvement, but in recipes where the first content is just the prep time, etc., that is making it into the description, which might be undesirable. It is probably a good idea to have one sentence descriptions to each recipe in the content preceding the prep time. I've also thought about including prep/cook time in the metadata and generating that portion automatically, which I will certainly implement when I feel up to it.

I've "fixed" a lot of "issues" produced above. The remaining issues in the first link I can't imagine as actually being problematic. It would be annoying to remove the `style` from `noscript` and I could imagine that causing breakage, etc.

One issue left is the sizing for mobile devices. I'll look into that later today as I have time.

**Comment by geowy** [comment]
You can do the `noscript`/`style` thing without invalidating your HTML like this:
```html
<style>
.js-only { display: none }
</style>

<script>
document.addEventListener("DOMContentLoaded", () => {
    for (e of document.getElementsByClassName("js-only")) {
        e.classList.remove("js-only")
    }
}
</script>

<div class="search js-only">
...
</div>
```

**Comment by LukeSmithxyz** [comment]
Yeah, I suppose I'll do it that way.
