### ISSUE TITLE
Images larger than 100kb

### ISSUE THREAD

**Issue by alpheratz0** [LukeSmithxyz/based.cooking#806]
Some images are ridiculously large, any plans on that?

I thought... maybe...

find static/pix -type f -size +100k -exec convert -resize 800x600 {} {} \\;

**Comment by LukeSmithxyz** [comment]
Yeah, actually. I was really picky early on, but with Hugo, there are ways of automatically generating smaller images when needed in webpages and otherwise optimizing them, so I've been allowing larger images now.

Right now, they're just taking up space indeed, but I'll be writing the system to optimize them as I get the time, possibly as early as next week.
